/**
 * Quote Generator: One-Click Scope of Works
 * Generates professional client quotes from TaskFlow projects
 * Designed for sales teams to eliminate manual typing
 */

export const generateScopeOfWorks = (project) => {
  if (!project) return null;

  const { title, client, priority, subtasks = [] } = project;
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Extract high-priority/incomplete subtasks for deliverables
  const deliverables = subtasks
    .filter((st) => !st.done) // Include only incomplete tasks
    .map((st) => st.text || st.label)
    .filter(Boolean);

  // Budget estimate based on project priority
  const budgetMap = { Low: '$1,500', Med: '$3,000', High: '$5,000+' };
  const estimatedBudget = budgetMap[priority] || '$3,000';

  // Generate the professional template
  const quote = `
╔════════════════════════════════════════════════════════════════════╗
║                     SCOPE OF WORKS                                 ║
╚════════════════════════════════════════════════════════════════════╝

PROJECT: ${title}
CLIENT: ${client}
DATE: ${date}
ESTIMATED BUDGET: ${estimatedBudget}

────────────────────────────────────────────────────────────────────

DELIVERABLES:

${
  deliverables.length > 0
    ? deliverables.map((item, idx) => `  ${idx + 1}. ${item}`).join('\n')
    : '  • Core project requirements\n  • Detailed specifications\n  • Delivery and support'
}

────────────────────────────────────────────────────────────────────

TIMELINE:
  • Project Kickoff: Immediate upon approval
  • Milestone Reviews: Bi-weekly
  • Final Delivery: Within agreed timeline
  • Post-Launch Support: 30 days included

TERMS:
  • Proposal valid for 30 days
  • 50% deposit required to commence work
  • Final payment due upon delivery
  • Change requests billed separately

────────────────────────────────────────────────────────────────────

This proposal is generated by TaskFlow.
Please review and confirm to proceed.

════════════════════════════════════════════════════════════════════
`.trim();

  return quote;
};

/**
 * Copy quote to clipboard and return success/failure
 */
export const copyQuoteToClipboard = (project) => {
  try {
    const quote = generateScopeOfWorks(project);
    navigator.clipboard.writeText(quote);
    return { success: true, message: 'Quote copied to clipboard!' };
  } catch (error) {
    console.error('Failed to copy quote:', error);
    return { success: false, message: 'Failed to copy. Try manually.' };
  }
};

/**
 * Download quote as .txt file
 */
export const downloadQuoteAsFile = (project) => {
  try {
    const quote = generateScopeOfWorks(project);
    const element = document.createElement('a');
    const file = new Blob([quote], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${project.title.replace(/\s+/g, '_')}_SOW.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    return { success: true, message: 'Quote downloaded!' };
  } catch (error) {
    console.error('Failed to download quote:', error);
    return { success: false, message: 'Download failed.' };
  }
};

/**
 * Format quote for email body (removes box drawing)
 */
export const formatQuoteForEmail = (project) => {
  const quote = generateScopeOfWorks(project);
  return quote.replace(/[╔╚║╗╝═╩╦]/g, '=').replace(/─/g, '-');
};
